import type { Metadata } from "next";
import "../styles/globals.css";
import Layout from "@/components/Layouts/Layout";

export const metadata: Metadata = {
  title: "Ski",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Layout>
       {children}
      </Layout>
  );
}
