- name: Déploiement de l’application Next.js
  hosts: web
  become: yes
  vars:
    repo_url: "git@github.com:alagh697/ski-exo-web-app.git"
    app_dir: "/home/ubuntu/app"
  tasks:
    - name: Mettre à jour le système
      apt:
        update_cache: yes
        upgrade: yes

    - name: Installer Node.js et PM2
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
        apt-get install -y nodejs
        npm install -g pm2

    - name: Cloner le projet
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"
        version: main
        force: yes

    - name: Installer les dépendances et builder
      shell: |
        cd {{ app_dir }}
        npm install
        npm run build

    - name: Démarrer l’application avec PM2
      shell: |
        cd {{ app_dir }}
        pm2 restart npm --name "next-app" -- run start || pm2 start npm --name "next-app" -- run start
        pm2 save
        pm2 startup
