name: CI/CD Next.js avec Ansible

on:
  push:
    branches:
      - main  # Déclenche l'action à chaque push sur main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code du projet
        uses: actions/checkout@v3

      - name: Installer Node.js et les dépendances
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run build

      - name: Copier les fichiers Ansible sur le serveur
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          source: "ansible/"
          target: "~/"

      - name: Exécuter Ansible pour le déploiement
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd ~/ansible
            ansible-playbook -i hosts.ini playbook.yml
